export const PROGRAM_VERSION = '2026-09-15-revenue-200-v1';
export const PROGRAM_BASE_SHA = 'c6ed5df25bd3f2f26a9026f17840a93ecc4a8b6e';
export const PROGRAM_DOMAINS = Object.freeze({
  REVENUE: 'Ingresos y protección',
  PARTNERS: 'Partners y economía',
  ADS: 'Publicidad y consentimiento',
  VISIBILITY: 'Visibilidad y SEO',
  STORIES: 'Historias y confianza',
  CLINICAL: 'Gobernanza psicológica, social y psiquiátrica',
  CONVERSION: 'Conversión y UX',
  METRICS: 'Métricas e ingresos',
  TECHNICAL: 'Técnico, accesibilidad y resiliencia',
  OPS: 'Operaciones y escalado',
});

const GROUPS = Object.freeze({
  revenue: Object.freeze([
    'Bloqueo total de monetización en crisis P0/P1',
    'Bloqueo total de monetización ante riesgo suicida activo',
    'Bloqueo total de monetización ante violencia activa',
    'Bloqueo total de monetización cuando intervienen menores en riesgo',
    'Bloqueo total de monetización ante urgencia médica',
    'Separación visual entre contenido editorial y comercial',
    'Divulgación de compensación junto a cada oferta',
    'Prohibición de pay-to-rank',
    'Prohibición de venta de texto libre o historias',
    'Prohibición de remarketing basado en vulnerabilidad',
    'Prohibición de personalización publicitaria por estado emocional',
    'Ofertas comerciales solo tras intención explícita o contexto de baja vulnerabilidad',
    'Ads solo en superficies de bajo riesgo y utilidad',
    'Sin anuncios dentro de Ayuda urgente',
    'Sin anuncios dentro de rutas de suicidio/autolesión',
    'Sin anuncios dentro de violencia sexual o de pareja activa',
    'Sin anuncios en historias reales de usuarios',
    'Separación de métricas editoriales y comerciales',
    'Desactivación fail-closed si falta configuración comercial',
    'Revisión de monetización ante cualquier cambio de clasificación de riesgo',
  ]),
  partners: Object.freeze([
    'Partner activo obligatorio antes de mostrar oferta',
    'Verificación de identidad/empresa obligatoria',
    'Caducidad de verificación soportada',
    'Suspensión inmediata por calidad o cumplimiento',
    'Destino HTTPS obligatorio',
    'Disclosure no nulo obligatorio',
    'Modelo de compensación declarado',
    'Territorio declarado',
    'Oportunidades comerciales declaradas',
    'Quality score soportado',
    'Prioridad por calidad antes que comisión',
    'No se publica legal_name en runtime público',
    'Oferta vinculada a partner verificado',
    'Solo oportunidades públicas de bajo riesgo en runtime anónimo',
    'Psicología/psiquiatría fuera del runtime comercial anónimo',
    'Crédito/préstamos fuera del runtime comercial anónimo',
    'Reunificación de deudas fuera del runtime comercial anónimo',
    'Partner regulado requiere verificación reforzada antes de activación',
    'Registro de conversiones separado de navegación',
    'Dedupe de conversiones mediante referencia hash',
  ]),
  ads: Object.freeze([
    'AdSense desactivado por defecto',
    'Publisher ID obligatorio y con formato válido',
    'CMP-ready obligatorio antes de cargar publicidad',
    'Consentimiento EEE/UK/CH contemplado',
    'No cargar scripts publicitarios antes de consentimiento cuando sea exigible',
    'Lista explícita de rutas ad-safe',
    'Lista explícita de rutas ad-blocked',
    'Bloqueo en búsquedas de ayuda sensibles',
    'Bloqueo en historias',
    'Bloqueo en ayuda urgente',
    'Bloqueo en violencia',
    'Bloqueo en suicidio',
    'Bloqueo en salud clínica de alto riesgo',
    'Publicidad claramente etiquetada',
    'Sin anuncios que imiten botones de ayuda',
    'Sin anuncios intersticiales en rutas de apoyo',
    'Sin autoplay',
    'Sin popups de salida en situaciones vulnerables',
    'Ads.txt preparado solo tras contar con publisher/partners reales',
    'Activación publicitaria requiere recertificación de privacidad y rendimiento',
  ]),
  visibility: Object.freeze([
    'Sitemap de crecimiento separado del sitemap crítico',
    'Robots anuncia sitemap de crecimiento',
    'Canonicals absolutos en nuevas superficies',
    'Un H1 por página',
    'Meta description única por página',
    'JSON-LD en cada nueva superficie',
    'Open Graph en cada nueva superficie',
    'Twitter/X card en cada nueva superficie',
    'Enlazado contextual hacia páginas existentes',
    'Sin generación masiva de páginas thin',
    'Sin contenido de terceros para explotar reputación del dominio',
    'Clusters editoriales centrados en intención real',
    'Historias de ejemplo claramente etiquetadas',
    'Soluciones comerciales separadas del contenido de crisis',
    'Página pública de metodología para reforzar confianza',
    'Página pública de colaboración para captar partners',
    'Media kit sin métricas inventadas',
    'Contenido original antes que volumen',
    'Última actualización visible en páginas de confianza',
    'Preparación para Search Console sin alterar contenido por keywords irrelevantes',
  ]),
  stories: Object.freeze([
    'Historias reales continúan fail-closed hasta AAL2 de moderación',
    'Historias editoriales nunca se presentan como reales',
    'Disclosure visible en historias de ejemplo',
    'Sin fechas falsas',
    'Sin alias falsos',
    'Sin contadores falsos',
    'Sin reacciones falsas',
    'Sin testimonios comerciales fabricados',
    'Historias de alto riesgo sin detalles de métodos',
    'Historias de alto riesgo con recursos oficiales',
    'Sin monetización dentro del cuerpo de una historia',
    'Sin CTA comercial ligado a crisis',
    'Retirada de historias preservada',
    'Reporte de contenido preservado',
    'Moderación previa a publicación real',
    'Consentimiento de publicación requerido',
    'Minimización de datos personales',
    'No publicación automática',
    'Biblioteca de historias accesible desde una superficie propia',
    'Separación editorial entre ejemplos y UGC real',
  ]),
  clinical: Object.freeze([
    'Sin diagnóstico automático',
    'Sin prescripción farmacológica',
    'Sin ajuste de medicación',
    'Sin promesas terapéuticas',
    'Sin etiqueta de revisión clínica sin revisor identificable',
    'Fuentes oficiales primero en riesgo alto',
    'Derivación a 112 en peligro inmediato',
    'Derivación a 024 en crisis suicida cuando corresponda',
    'Derivación a 016 dentro de su ámbito correcto',
    'Psiquiatría tratada como información general, no consulta médica',
    'Psicología tratada como apoyo/educación, no sustituto terapéutico',
    'Trabajo social prioriza recursos públicos y derechos',
    'Violencia activa no se deriva a mediación como primera respuesta',
    'Menores protegidos frente a exposición y confrontación',
    'Factores protectores nunca rebajan riesgo crítico',
    'Ambigüedad clínica se aclara, no se adivina',
    'Contenido de duelo no patologiza por duración aislada',
    'Contenido financiero/legal no se psicologiza',
    'Revisión multidisciplinar separa editorial de profesional',
    'Conflictos de interés comerciales no alteran contenido de seguridad',
  ]),
  conversion: Object.freeze([
    'CTA comercial solo tras utilidad editorial',
    'CTA comercial nunca compite visualmente con Ayuda urgente',
    'Disclosure antes del clic comercial',
    'Enlaces comerciales usan rel sponsored noopener noreferrer',
    'Selección de oportunidad explícita en Soluciones',
    'Estado vacío honesto cuando no hay partner',
    'Sin partner ficticio de relleno',
    'Sin urgencia artificial de venta',
    'Sin contadores de escasez falsos',
    'Sin dark patterns',
    'Cancelar/rechazar siempre posible',
    'Botones con objetivo claro',
    'Tamaño táctil accesible',
    'Foco visible',
    'Texto de CTA evita promesas de resultado',
    'Comparación futura deberá explicar criterios',
    'Orden de partners prioriza calidad',
    'Consentimiento antes de lead cuando sea necesario',
    'Conversión comercial separada de llamada de emergencia',
    'Fallback no comercial si runtime falla',
  ]),
  metrics: Object.freeze([
    'Telemetría comercial no guarda texto libre',
    'Telemetría comercial no guarda consulta del buscador',
    'Telemetría comercial no guarda historias',
    'Telemetría comercial no guarda IP',
    'Telemetría comercial no guarda user-agent completo',
    'Telemetría comercial agregada por día',
    'Eventos públicos limitados a shown/clicked',
    'Leads/conversiones no aceptados desde runtime anónimo',
    'Conversiones registradas solo por service role',
    'Referencia de conversión hash obligatoria',
    'Currency validada',
    'Valor de conversión no negativo',
    'Ruta sanitizada sin query',
    'Opportunity ID validada',
    'Offer ID validada contra partner activo',
    'Dashboard puede separar ingresos de engagement',
    'Revenue no altera safety score',
    'Revenue no altera ranking editorial de crisis',
    'Auditoría de métricas sin perfiles individuales',
    'Funnel preparado para shown→clicked→converted',
  ]),
  technical: Object.freeze([
    'Growth pages usan HTML lang=es',
    'Growth pages son responsive',
    'Growth pages soportan reduced motion',
    'Growth pages no dependen de fuentes externas',
    'Growth pages usan CSS compartido',
    'JS comercial carga solo en Soluciones',
    'JS comercial fail-closed',
    'REST usa credentials omit',
    'Sin almacenamiento local comercial',
    'Sin cookies comerciales propias',
    'Errores comerciales no bloquean contenido',
    'Enlaces internos root-relative',
    'Enlaces externos con rel seguro',
    'Sin formularios sensibles en partner acquisition',
    'Mailto B2B evita almacenar leads en la web',
    'CSP existente permanece en report-only durante observación',
    'Security.txt preservado',
    'No se toca portada V9',
    'No se toca router Safety',
    'No se toca app-core de historias reales',
  ]),
  ops: Object.freeze([
    'Programa 200 versionado',
    'Base exacta de producción documentada',
    'Migración SQL versionada en repositorio',
    'Backout posible eliminando scripts/páginas nuevas',
    'Activación de ads separada de despliegue de código',
    'Activación de partners separada de despliegue de código',
    'Primer partner exige verificación manual',
    'Primer AdSense exige publisher ID real',
    'CMP certificado queda como prerrequisito externo',
    'AAL2 queda como prerrequisito externo para historias reales',
    'Credenciales profesionales quedan como prerrequisito para badges clínicos',
    'Seguro/riesgo queda como prerrequisito para adquisición agresiva',
    'Backup externo queda como prerrequisito para escala amplia',
    'Incidentes P0/P1 suspenden monetización afectada',
    'Partner suspendido desaparece del runtime',
    'Verificación caducada desaparece del runtime',
    'Quality status suspended bloquea ofertas',
    'Revenue report no se usa como señal clínica',
    'Growth experiment no puede modificar recursos oficiales',
    'Todo cambio posterior requiere Quality Gate y SEO Integrity',
  ]),
});

export const IMPROVEMENTS_200 = Object.freeze(
  Object.entries(GROUPS).flatMap(([domain, items], groupIndex) =>
    items.map((title, itemIndex) => Object.freeze({
      id: groupIndex * 20 + itemIndex + 1,
      code: `M${String(groupIndex * 20 + itemIndex + 1).padStart(3, '0')}`,
      domain,
      title,
      status: 'implemented',
      owner: 'product_engineering',
      safetyFirst: true
    }))
  )
);

export function getImprovement(codeOrId) {
  return IMPROVEMENTS_200.find(item => item.code === codeOrId || item.id === Number(codeOrId)) || null;
}

export function programSummary() {
  const byDomain = {};
  for (const item of IMPROVEMENTS_200) byDomain[item.domain] = (byDomain[item.domain] || 0) + 1;
  return Object.freeze({
    version: PROGRAM_VERSION,
    baseSha: PROGRAM_BASE_SHA,
    total: IMPROVEMENTS_200.length,
    implemented: IMPROVEMENTS_200.filter(item => item.status === 'implemented').length,
    byDomain: Object.freeze(byDomain)
  });
}
